from textual.theme import Theme

DEFAULT_THEMES = {
    "adwaita-dark": Theme(
        name="adwaita-dark",
        primary="#303030",
        secondary="#3d3d3d",
        accent="#3584e4",
        foreground="#eeeeec",
        background="#242424",
        surface="#353535",
        panel="#3d3d3d",
        success="#26a269",
        warning="#f8e45c",
        error="#c01c28",
        dark=True,
    ),
    "adwaita-light": Theme(
        name="adwaita-light",
        primary="#ebebeb",
        secondary="#dcdcdc",
        accent="#3584e4",
        foreground="#3d3d3d",
        background="#fafafa",
        surface="#f0f0f0",
        panel="#dcdcdc",
        success="#26a269",
        warning="#f8e45c",
        error="#c01c28",
        dark=False,
    ),
    "dracula": Theme(
        name="dracula",
        primary="#44475a",
        secondary="#6272a4",
        accent="#bd93f9",
        foreground="#f8f8f2",
        background="#282a36",
        surface="#343746",
        panel="#44475a",
        success="#50fa7b",
        warning="#f1fa8c",
        error="#ff5555",
        dark=True,
    ),
    "nord": Theme(
        name="nord",
        primary="#434c5e",
        secondary="#4c566a",
        accent="#88c0d0",
        foreground="#eceff4",
        background="#2e3440",
        surface="#3b4252",
        panel="#434c5e",
        success="#a3be8c",
        warning="#ebcb8b",
        error="#bf616a",
        dark=True,
    ),
    "osaka-jade": Theme(
        name="osaka-jade",
        primary="#003f4a",
        secondary="#005a66",
        accent="#2aa198",
        foreground="#c5c8c6",
        background="#002731",
        surface="#00313f",
        panel="#003f4a",
        success="#589d75",
        warning="#b58900",
        error="#dc322f",
        dark=True,
    ),
    "rosepine": Theme(
        name="rosepine",
        primary="#31748f",
        secondary="#908caa",
        accent="#eb6f92",
        foreground="#e0def4",
        background="#191724",
        surface="#1f1d2e",
        panel="#26233a",
        success="#9ccfd8",
        warning="#f6c177",
        error="#eb6f92",
        dark=True,
    ),
    "cyberpunk": Theme(
        name="cyberpunk",
        primary="#ff00ff",
        secondary="#00ff9f",
        accent="#ff00ff",
        foreground="#f0f0f0",
        background="#0c0c1c",
        surface="#1a1a3a",
        panel="#1a1a3a",
        success="#00ff9f",
        warning="#f0f0f0",
        error="#ff00ff",
        dark=True,
    ),
}
